console.log("Leave a secret massage");
alert('Hello techer');
prompt('test1');
var txt= document.getElementById ('goodmen')
innerHTML= "koda ba maste .";
var name1 = prompt("what is your name?", "mohsen");
document.write(name1);
var date= date();
document.write(date + '<br>')
var loction = window.location;
document.write(loction+ "<br>");
var width = window.innerWidth;
document.write (width + '<br>');
var pi= 3.14;
document.write (pi + '<br>')
var status =false ;
document.write(false + '<br>')
var status =window.closed ;
document.write(window.closed + '<br>');
var x= 45+5;
document.write(x +'<br>'  );
var x= 1799-3;
document.write(x +'<br>'  );
var x= 1045*4;
document.write(x +'<br>'  );
var x= 45/4;
document.write(x +'<br>'  );
var x= 45%4;
document.write(x +'<br>'  );
var name = "mohsen" +"   "+" mandana "
document.write (name1 +'<br>');
var name1 = "mohsen"+"   "+  400
document.write (name1+'<br>') ;
var txt=document.getElementById('paragrap');
txt=document="mamnon ostsd khob";
var number2 = 7
var number3 = 3
document.write(number2<=number3  , "<br>");
document.write(number2==number3   , '<br>');
var number5=34;
var number6=38;
if(number5>=number6)
{
     alert("bozorg");
}
var g= 77;
var v= 44;
document.write((v==22)||(g==77) + '<br>');
var g = 2707;
var v = 41;
document.write((7454>v)&&(v>77) +'<br>');
function sallam(){
    alert("sallam ostad");
}sallam();

function class1 (web) {

    document.write(web + '<br>');
}

class1("hello");